-- =========================================================
-- PORTAL SAMALI - SUPABASE DATABASE
-- Jalankan di Supabase SQL Editor
-- =========================================================

create table if not exists public.kegiatan (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  time text,
  detail text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sensus_jamaah (
  id bigint generated by default as identity primary key,
  no integer,
  kode_kelg text,
  pref text,
  nama text not null,
  lp text,
  ttl text,
  umur integer default 0,
  status_bk text,
  status text,
  alamat text,
  telepon text,
  ket text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Realtime
alter table public.kegiatan replica identity full;
alter table public.sensus_jamaah replica identity full;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'kegiatan'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.kegiatan;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'sensus_jamaah'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sensus_jamaah;
  END IF;
END $$;

-- RLS untuk akses browser menggunakan publishable/anon key.
-- CATATAN: ini mode awal agar Portal Samali dapat CRUD langsung.
-- Setelah Supabase Auth siap, ganti policy ini dengan policy berbasis user/role.
alter table public.kegiatan enable row level security;
alter table public.sensus_jamaah enable row level security;

drop policy if exists "samali_kegiatan_select" on public.kegiatan;
drop policy if exists "samali_kegiatan_insert" on public.kegiatan;
drop policy if exists "samali_kegiatan_update" on public.kegiatan;
drop policy if exists "samali_kegiatan_delete" on public.kegiatan;
create policy "samali_kegiatan_select" on public.kegiatan for select to anon, authenticated using (true);
create policy "samali_kegiatan_insert" on public.kegiatan for insert to anon, authenticated with check (true);
create policy "samali_kegiatan_update" on public.kegiatan for update to anon, authenticated using (true) with check (true);
create policy "samali_kegiatan_delete" on public.kegiatan for delete to anon, authenticated using (true);

drop policy if exists "samali_sensus_select" on public.sensus_jamaah;
drop policy if exists "samali_sensus_insert" on public.sensus_jamaah;
drop policy if exists "samali_sensus_update" on public.sensus_jamaah;
drop policy if exists "samali_sensus_delete" on public.sensus_jamaah;
create policy "samali_sensus_select" on public.sensus_jamaah for select to anon, authenticated using (true);
create policy "samali_sensus_insert" on public.sensus_jamaah for insert to anon, authenticated with check (true);
create policy "samali_sensus_update" on public.sensus_jamaah for update to anon, authenticated using (true) with check (true);
create policy "samali_sensus_delete" on public.sensus_jamaah for delete to anon, authenticated using (true);
